# workflow for integrating in CI/CD pipeline, creating docker image and pushing it into the repository

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Build:checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.CI_CD_REPO_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
       context: .
       push: true
       tags: ${{ steps.meta.outputs.tags }}
       labels: ${{ steps.meta.outputs.labels }}



#    - name: Login to GitHub Packages
#      uses: docker/login-action@v1
#      with:
#        registry: ghcr.io
#        username: ${{ github.actor }}
#        password: ${{ secrets.CI_CD_REPO_TOKEN }}
#    - name: Build and push Docker image
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        push: true
#        tags: ghcr.io/${{ github.repository }}:${{ github.sha }}



#    - name: Build Docker Image
#      run: docker build . --tag archiver-api:latest

#    - name: Log into GHCR
#     run: echo "${{ secrets.CI_CD_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      
#    - name: Push image to GHCR
#      run: |
#        IMAGE_ID=ghcr.io/${{github.repository_owner}}/archiver-api:latest
#        docker tag archiver-api:latest $IMAGE_ID
#        docker image push $IMAGE_ID
